app:
 
  # use the Dockerfile next to this file
  build: .
 
  # sources environment variable configuration for our app
  env_file: .env
 
  # rely on the RAILS_ENV value of the host machine
  environment:
    RAILS_ENV: $RAILS_ENV
 
  # makes the app container aware of the DB container
  links:
    - db
 
  # expose the port we configured Unicorn to bind to
  ports:
    - "3000:3000"
    # map our application source code, in full, to the application root of our container
  volumes:
    - .:/home/emacias/Work/Taller/tap
db:
 
  # use the preferred version of the official Postgres image
  # see https://hub.docker.com/_/postgres/
  image: mysql:5.6
  ports:
    - "3306:3306" 
  # persist the database between containers by storing it in a volume
  volumes:
    - docker-tap-mysql:/var/lib/mysql/data
  env_file:
    - '.env.db'
